use AdventureWorksDW2017;

/*1.	What are the sales, product costs, profit, number of orders
 & quantity ordered for internet sales by product category and ranked by sales?*/

SELECT DENSE_RANK() OVER  (order by sum (Sales.SalesOrderHeader.TotalDue) desc) as Ranking,
DC.ENGLISHPRODUCTCATEGORYNAME,FS.ORDERQUANTITY,FS.UNITPRICE,
SUM(FS.ORDERQUANTITY)AS No_of_ORDERS,
SUM(FS.ORDERQUANTITY*FS.SALESAMOUNT) AS TOTAL_SALES,
(FS.SALESAMOUNT-FS.TOTALPRODUCTCOST)*SUM(FS.ORDERQUANTITY) AS PROFIT
FROM DBO.DIMPRODUCT DP, DBO.DIMPRODUCTSUBCATEGORY
DS,DBO.DIMPRODUCTCATEGORY DC, DBO.FACTINTERNETSALES FS
WHERE DP.PRODUCTSUBCATEGORYKEY=DS.PRODUCTSUBCATEGORYKEY
AND DS.PRODUCTCATEGORYKEY=DC.PRODUCTCATEGORYKEY
AND DP.PRODUCTKEY=FS.PRODUCTKEY
GROUP BY DC.ENGLISHPRODUCTCATEGORYNAME,FS.ORDERQUANTITY,FS.UNITPRICE,FS.SALESAMOUNT, FS.TOTALPRODUCTCOST
ORDER BY TOTAL_SALES DESC;

/*(46 rows affected)*/

/*2.What are the sales, product costs, profit, number of orders & 
quantity ordered for reseller sales by product category and ranked by sales?*/

SELECT DPC.ENGLISHPRODUCTCATEGORYNAME ,FIS.ORDERQUANTITY,
SUM(FIS.ORDERQUANTITY) AS NOOFORDERS,
SUM(FIS.ORDERQUANTITY*FIS.SALESAMOUNT) AS TOTALSALES,
(FIS.SALESAMOUNT-FIS.TOTALPRODUCTCOST)*(FIS.ORDERQUANTITY) AS PROFIT
FROM DBO.DimProduct DP, DBO.DIMPRODUCTSUBCATEGORY
DSC,DBO.DIMPRODUCTCATEGORY DPC,DBO.FACTRESELLERSALES FIS
WHERE DP.PRODUCTSUBCATEGORYKEY=DSC.PRODUCTSUBCATEGORYKEY
AND DSC.PRODUCTCATEGORYKEY=DPC.PRODUCTCATEGORYKEY
AND DP.PRODUCTKEY=FIS.PRODUCTKEY
GROUP BY
DPC.ENGLISHPRODUCTCATEGORYNAME,FIS.ORDERQUANTITY ,FIS.SALESAMOUNT,
FIS.TOTALPRODUCTCOST
ORDER BY TOTALSALES DESC;

/*(1556 rows affected)*/

/*3.	What are the sales, product costs, profit, number of orders & 
quantity ordered for both internet & reseller sales by product category and ranked by sales?*/

SELECT DC.ENGLISHPRODUCTCATEGORYNAME ,
F.ORDERQUANTITY,
F.UNITPRICE AS INTERNET,
FI.UNITPRICE AS RESELLER,
SUM(F.ORDERQUANTITY+FI.ORDERQUANTITY) AS NOOFORDERS,
SUM(F.ORDERQUANTITY*F.SALESAMOUNT) + SUM(FI.ORDERQUANTITY*FI.SALESAMOUNT) AS SALES,
SUM((F.SALESAMOUNT-F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY) +
(FI.SALESAMOUNT-FI.TOTALPRODUCTCOST)*(FI.ORDERQUANTITY))AS PROFIT
FROM DBO.DIMPRODUCT DP, DBO.DIMPRODUCTSUBCATEGORY DS,DBO.DIMPRODUCTCATEGORY DC,DBO.FACTRESELLERSALES
F,DBO.FACTINTERNETSALES FI
WHERE DP.PRODUCTSUBCATEGORYKEY=DS.PRODUCTSUBCATEGORYKEY
AND DS.PRODUCTCATEGORYKEY=DC.PRODUCTCATEGORYKEY
AND DP.PRODUCTKEY=F.PRODUCTKEY
AND DP.PRODUCTKEY=FI.PRODUCTKEY
GROUP BY
DC.ENGLISHPRODUCTCATEGORYNAME,F.ORDERQUANTITY,F.UNITPRICE,F.SALESAMOUNT,F.TOTALPRODUCTCOST,FI.ORDERQUANTITY,FI.SALESAMOUNT,FI.TOTALPRODUCTCOST,FI.UNITPRICE
	ORDER BY SALES DESC;

/*(691 rows affected)*/

/*4.	What are the sales, product costs, profit, number of orders & quantity ordered for product category Accessories broken-down by Product Hierarchy 
(Category, Subcategory, Model & Product) for both internet & reseller sales?*/

SELECT DC.ENGLISHPRODUCTCATEGORYNAME
,DS.ENGLISHPRODUCTSUBCATEGORYNAME,DP.ENGLISHPRODUCTNAME,DP.MODELNAME
,F.ORDERQUANTITY,F.UNITPRICE AS INTERNET,FI.UNITPRICE AS RESELLER,
SUM(F.ORDERQUANTITY+FI.ORDERQUANTITY) AS NOOFORDERS,
SUM(F.ORDERQUANTITY*F.SALESAMOUNT) + SUM(FI.ORDERQUANTITY*FI.SALESAMOUNT) AS TOTALSALES, SUM((F.SALESAMOUNT-F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY) + (FI.SALESAMOUNT-FI.TOTALPRODUCTCOST)*(FI.ORDERQUANTITY))
AS PROFIT
FROM DBO.DIMPRODUCT DP, DBO.DIMPRODUCTSUBCATEGORY DS, DBO.DIMPRODUCTCATEGORY DC, DBO.FACTRESELLERSALES F,DBO.FACTINTERNETSALES FI WHERE DP.PRODUCTSUBCATEGORYKEY=DS.PRODUCTSUBCATEGORYKEY
AND DS.PRODUCTCATEGORYKEY=DC.PRODUCTCATEGORYKEY
AND DP.PRODUCTKEY=F.PRODUCTKEY
AND DP.PRODUCTKEY=FI.PRODUCTKEY
AND DC.ENGLISHPRODUCTCATEGORYNAME='ACCESSORIES'
GROUP BY DC.ENGLISHPRODUCTCATEGORYNAME
,F.ORDERQUANTITY,F.UNITPRICE,F.SALESAMOUNT,F.TOTALPRODUCTCOST,
FI.ORDERQUANTITY,FI.SALESAMOUNT,FI.TOTALPRODUCTCOST,FI.UNITPRICE,DS.ENGLISHPRODUCTSUBCATEGORYNAME,DP.ENGLISHPRODUCTNAME,DP.MODELNAME
ORDER BY TOTALSALES DESC;

/*5.	What are the sales, product costs, profit, number of orders & 
quantity ordered for both internet & reseller sales by country and ranked by sales?*/

SELECT DISTINCT DG.ENGLISHCOUNTRYREGIONNAME,
SUM(F.ORDERQUANTITY) AS RESELLERNOOFQUANTITY,
SUM(Fi.ORDERQUANTITY) AS INTERNETNOOFQUANTITY,
COUNT(F.ORDERQUANTITY) AS NO_OF_ORDERS_FOR_RESELLER,
COUNT(Fi.ORDERQUANTITY) AS NOOFORDERSFORINTERNET,
SUM(F.ORDERQUANTITY*F.SALESAMOUNT) AS RESELLERSALES,
SUM(Fi.ORDERQUANTITY*Fi.SALESAMOUNT) AS INTERNETSALES,
SUM((F.SALESAMOUNT-F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY)) AS RESELLERPROFIT,
SUM((Fi.SALESAMOUNT-Fi.TOTALPRODUCTCOST)*(Fi.ORDERQUANTITY)) AS INTERNETPROFIT
FROM DBO.DIMPRODUCT DP,DBO.DIMPRODUCTSUBCATEGORY DS,DBO.DIMPRODUCTCATEGORY
DC, DBO.FACTRESELLERSALES F,DBO.FACTINTERNETSALES Fi, DBO.DIMCUSTOMER DCS,
DBO.DIMGEOGRAPHY DG,DBO.DIMRESELLER DR
WHERE DP.PRODUCTSUBCATEGORYKEY=DS.PRODUCTSUBCATEGORYKEY
AND DS.PRODUCTCATEGORYKEY=DC.PRODUCTCATEGORYKEY
AND DP.PRODUCTKEY=F.PRODUCTKEY
AND DP.PRODUCTKEY=Fi.PRODUCTKEY
AND Fi.CUSTOMERKEY=DCS.CUSTOMERKEY
AND DCS.GEOGRAPHYKEY=DG.GEOGRAPHYKEY
AND DG.GEOGRAPHYKEY=DR.GEOGRAPHYKEY
GROUP BY DG.ENGLISHCOUNTRYREGIONNAME
ORDER BY INTERNETSALES DESC ,RESELLERSALES DESC;

/*(6 rows affected)*/

/*6.	What are the sales, product costs, profit, number of orders & quantity ordered 
for France by city and ranked by sales for both internet & reseller sales?*/


SELECT DISTINCT DG.ENGLISHCOUNTRYREGIONNAME,DG.CITY
,SUM(F.ORDERQUANTITY) AS RESELLERNOOFQUANTITY,SUM(Fi.ORDERQUANTITY)AS INTERNETNOOFQUANTITY,
COUNT(F.ORDERQUANTITY) AS NOOFORDERSFORRESELLER,COUNT(Fi.ORDERQUANTITY)
AS NOOFORDERSFORINTERNET,
SUM(F.ORDERQUANTITY*F.SALESAMOUNT) AS RESELLERSALES,
SUM(Fi.ORDERQUANTITY*Fi.SALESAMOUNT) AS INTERNETSALES,
SUM((F.SALESAMOUNT-F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY)) AS RESELLERPROFIT,
SUM((Fi.SALESAMOUNT-Fi.TOTALPRODUCTCOST)*(Fi.ORDERQUANTITY)) AS INTERNETPROFIT
FROM DBO.DIMPRODUCT DP
JOIN DBO.DIMPRODUCTSUBCATEGORY DS
ON DP.PRODUCTSUBCATEGORYKEY=DS.PRODUCTSUBCATEGORYKEY
JOIN DBO.DIMPRODUCTCATEGORY DC
ON DS.PRODUCTCATEGORYKEY=DC.PRODUCTCATEGORYKEY
JOIN DBO.FACTRESELLERSALES F
ON DP.PRODUCTKEY=F.PRODUCTKEY
JOIN DBO.FACTINTERNETSALES Fi
ON DP.PRODUCTKEY=Fi.PRODUCTKEY
JOIN DBO.DIMCUSTOMER DCS
ON Fi.CUSTOMERKEY=DCS.CUSTOMERKEY
JOIN DBO.DIMGEOGRAPHY DG
ON DCS.GEOGRAPHYKEY=DG.GEOGRAPHYKEY
JOIN DBO.DIMRESELLER DR
ON DG.GEOGRAPHYKEY=DR.GEOGRAPHYKEY
WHERE DG.ENGLISHCOUNTRYREGIONNAME='FRANCE'
GROUP BY DG.ENGLISHCOUNTRYREGIONNAME,DG.CITY
ORDER BY [INTERNETSALES] DESC ,RESELLERSALES DESC;\


/*(21 rows affected)*/

/*7.	What are the top ten resellers by reseller hierarchy (business type, reseller name) ranked by sales?*/

SELECT TOP 10 DR.RESELLERNAME,DR.BUSINESSTYPE,SUM(F.ORDERQUANTITY*F.SALESAMOUNT) AS
SALES FROM DBO.DIMRESELLER DR, DBO.FACTRESELLERSALES F
WHERE DR.RESELLERKEY=F.RESELLERKEY
GROUP BY DR.RESELLERNAME,DR.BUSINESSTYPE
ORDER BY SALES DESC;

/*(10 rows affected)*/


/*8.	What are the top ten (internet) customers ranked by sales?*/

SELECT CONCAT_WS(' ',E.FIRSTNAME,E.MIDDLENAME,E.LASTNAME) AS EMPLOYEENAME,
SUM(FRS.SALESAMOUNT*FRS.ORDERQUANTITY) AS SALESAMOUNT
FROM FACTRESELLERSALES AS FRS INNER JOIN DIMEMPLOYEE AS E
ON FRS.EMPLOYEEKEY=E.EMPLOYEEKEY
GROUP BY E.FIRSTNAME,E.MIDDLENAME,E.LASTNAME
ORDER BY SALESAMOUNT DESC;

/*(17 rows affected)*/


/*9.	What are the sales, product costs, profit, number of orders & quantity ordered by Customer Occupation?*/

SELECT DC.ENGLISHOCCUPATION ,COUNT(F.ORDERQUANTITY) AS NUMBEROFORDERS,SUM(F.ORDERQUANTITY) AS QUANTITYORDERED
,SUM(F.ORDERQUANTITY*F.SALESAMOUNT) AS SALES
,SUM((F.SALESAMOUNT-F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY)) AS PROFIT
FROM DBO.DIMCUSTOMER DC,DBO.FACTINTERNETSALES F
WHERE DC.CUSTOMERKEY=F.CUSTOMERKEY
GROUP BY DC.ENGLISHOCCUPATION
ORDER BY SALES;

/*(5 rows affected)*/

/*10.	What are the ranked sales of the sales people (employees)?*/

SELECT CONCAT_WS(' ',E.FIRSTNAME,E.MIDDLENAME,E.LASTNAME) AS 'EMPLOYEE NAME',
SUM(F.SALESAMOUNT*F.ORDERQUANTITY) AS SALESAMOUNT
FROM FACTRESELLERSALES AS F INNER JOIN DIMEMPLOYEE AS E
ON F.EMPLOYEEKEY=E.EMPLOYEEKEY
GROUP BY E.FIRSTNAME,E.MIDDLENAME,E.LASTNAME
ORDER BY SALESAMOUNT DESC;


/*(17 rows affected)*/

/*11.	What are the sales, discount amounts (promotion discounts), profit and promotion % 
of sales for Reseller Sales by Promotion Hierarchy (Category, Type & Name) – sorted descending by sales.?*/


SELECT DP.ENGLISHPROMOTIONCATEGORY,DP.ENGLISHPROMOTIONTYPE,DP.ENGLISHPROMOTIONNAME, SUM((DP.DISCOUNTPCT*F.SALESAMOUNT)) AS DISCOUNTAMOUNTS,
F.DISCOUNTAMOUNT,SUM(F.ORDERQUANTITY*((F.SALESAMOUNT)-
(DP.DISCOUNTPCT*F.SALESAMOUNT))) AS SALES,
SUM((((F.SALESAMOUNT)-(DP.DISCOUNTPCT*F.SALESAMOUNT))-
F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY)) AS PROFIT,
100*(SUM((DP.DISCOUNTPCT*F.SALESAMOUNT)))/SUM(F.ORDERQUANTITY*((F.SALESAMOUNT
)-(DP.DISCOUNTPCT*F.SALESAMOUNT))) AS PercentOFPROMOTIONSALE
FROM DBO.DIMPROMOTION DP
JOIN DBO.FACTRESELLERSALES F
ON DP.PROMOTIONKEY=F.PROMOTIONKEY
GROUP BY
DP.ENGLISHPROMOTIONCATEGORY,DP.ENGLISHPROMOTIONTYPE,DP.ENGLISHPROMOTIONNAME,DP.DISCOUNTPCT,F.DISCOUNTAMOUNT
ORDER BY SALES DESC;


/*(514 rows affected)*/

/*12.	What are the sales, product costs, profit, number of orders & quantity ordered by Sales Territory Hierarchy 
(Group, Country, region) and ranked by sales for both internet & reseller sales?*/

SELECT DT.SALESTERRITORYGROUP,DT.SALESTERRITORYCOUNTRY,DT.SALESTERRITORYREGION,
SUM(F.ORDERQUANTITY) AS RESELLERNOOFQUANTITY,SUM(FCT.ORDERQUANTITY) AS
INTERNETNOOFQUANTITY,
COUNT(F.ORDERQUANTITY) AS NOOFORDERSFORRESELLER,COUNT(FCT.ORDERQUANTITY)
AS NOOFORDERSFORINTERNET,
SUM(F.ORDERQUANTITY*F.SALESAMOUNT) AS RESELLERSALES,
SUM(FCT.ORDERQUANTITY*FCT.SALESAMOUNT) AS INTERNETSALE,
SUM((F.SALESAMOUNT-F.TOTALPRODUCTCOST)*(F.ORDERQUANTITY)) AS RESELLERPROFIT,
SUM((FCT.SALESAMOUNT-FCT.TOTALPRODUCTCOST)*(FCT.ORDERQUANTITY)) AS INTERNETPROFIT
FROM DBO.DIMSALESTERRITORY DT, DBO.FACTINTERNETSALES F,DBO.FACTRESELLERSALES
FCT
WHERE DT.SALESTERRITORYKEY=F.SALESTERRITORYKEY
AND FCT.SALESTERRITORYKEY=DT.SALESTERRITORYKEY
GROUP BY
DT.SALESTERRITORYGROUP,DT.SALESTERRITORYCOUNTRY,DT.SALESTERRITORYREGION;

/*(10 rows affected)*/


/*13.	What are the sales by year by sales channels (internet, reseller & total)?*/

SELECT FSQ.CALENDARYEAR AS YEAR, SUM(FIS.ORDERQUANTITY*FIS.SALESAMOUNT) AS
INTERNETSALES, SUM(F.ORDERQUANTITY*F.SALESAMOUNT) AS RESELLERSALES, SUM(FIS.ORDERQUANTITY*FIS.SALESAMOUNT)+SUM(F.ORDERQUANTITY*F.SALESAMOUNT)
AS TOTALSALES
FROM FACTSALESQUOTA AS FSQ JOIN DIMEMPLOYEE AS E
ON FSQ.EMPLOYEEKEY=E.EMPLOYEEKEY JOIN FACTRESELLERSALES AS F
ON E.EMPLOYEEKEY=F.EMPLOYEEKEY JOIN DIMPRODUCT AS P
ON F.PRODUCTKEY=P.PRODUCTKEY JOIN FACTINTERNETSALES AS FIS
ON FIS.PRODUCTKEY=P.PRODUCTKEY
GROUP BY FSQ.CALENDARYEAR
ORDER BY INTERNETSALES DESC;

/*(4 rows affected)*/


/*14.	What are the total sales by month (& year)?*/

SELECT MONTH(FSQ.DATE) AS MONTH, YEAR(FSQ.DATE) AS YEAR,
SUM(FIS.ORDERQUANTITY*FIS.SALESAMOUNT)+SUM(F.ORDERQUANTITY*F.SALESAMOUNT)
AS TOTALSALES
FROM FACTSALESQUOTA AS FSQ JOIN DIMEMPLOYEE AS E
ON FSQ.EMPLOYEEKEY=E.EMPLOYEEKEY JOIN FACTRESELLERSALES AS F
ON E.EMPLOYEEKEY=F.EMPLOYEEKEY JOIN DIMPRODUCT AS P
ON F.PRODUCTKEY=P.PRODUCTKEY JOIN FACTINTERNETSALES AS FIS
ON FIS.PRODUCTKEY=P.PRODUCTKEY
GROUP BY MONTH(FSQ.DATE), YEAR(FSQ.DATE)
ORDER BY TOTALSALES DESC;

/*(12 rows affected)*/

